import fs from "node:fs";

const manifest = readJson("manifest.json");
const packageJson = readJson("package.json");
const packageLock = readJson("package-lock.json");
const versions = readJson("versions.json");
const errors = [];

if (!/^\d+\.\d+\.\d+$/.test(manifest.version)) errors.push("manifest version must be x.y.z");
if (!/^[a-z][a-z-]*$/.test(manifest.id) || manifest.id.includes("obsidian") || manifest.id.endsWith("plugin")) {
  errors.push("manifest id does not satisfy Obsidian community rules");
}
if (manifest.version !== packageJson.version) errors.push("package.json version differs from manifest");
if (manifest.version !== packageLock.version) errors.push("package-lock.json version differs from manifest");
if (packageLock.packages?.[""]?.version !== manifest.version) errors.push("package-lock root package version differs");
if (versions[manifest.version] !== manifest.minAppVersion) errors.push("versions.json is missing the current compatibility entry");
if (!manifest.name || !manifest.author || !manifest.description) errors.push("manifest required text fields are missing");
if (typeof manifest.isDesktopOnly !== "boolean") errors.push("manifest isDesktopOnly must be boolean");

for (const file of ["README.md", "LICENSE", "manifest.json", "main.js", "styles.css"]) {
  if (!fs.existsSync(file)) errors.push(`${file} is missing`);
}
if (fs.existsSync("main.js")) {
  const bundle = fs.readFileSync("main.js", "utf8");
  if (!bundle.startsWith("/* Generated by esbuild.")) errors.push("main.js is not the production bundle");
  if (bundle.includes("sourceMappingURL=data:")) errors.push("main.js contains an inline source map");
}

if (errors.length) {
  errors.forEach((error) => console.error(`- ${error}`));
  process.exit(1);
}
console.log(`Release validation passed for ${manifest.id} ${manifest.version}.`);

function readJson(path) {
  return JSON.parse(fs.readFileSync(path, "utf8"));
}
